# Generated by Django 5.2.1 on 2025-06-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(default='https://ik.imagekit.io/dragunov/default.jpg?updatedAt=1749255658947'),
        ),
    ]
