# Generated by Django 5.2.1 on 2025-06-07 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_image_file_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image_file',
            new_name='upload_image_file',
        ),
    ]
