# Generated by Django 5.2.1 on 2025-06-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(default='https://ik.imagekit.io/dragunov/profile_pics/default.jpg?updatedAt=1749236584228'),
        ),
    ]
