# Generated by Django 5.2.1 on 2025-06-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoussawiApp', '0002_comment_like_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
